### ISSUE TITLE
Lost Media Search - Fairy Mod for Beta 1.7.3

### ISSUE THREAD

**Issue by GorlathStreams** [KodaichiZero/HeyLookFairies-1.12.2#12]
Hello. First off, sorry for posting here since I'm pretty sure this isn't what issues are supposed to be about lol, but I was having trouble figuring out how to contact you otherwise. I have been backing up several of your mods, and while most are still available or have been backed up already, the Fairy Mod's b1.7.3 version (and, tbh, any versions earlier than 1.6.4) has proven itself to be, as far as I am concerned, lost media, and I was wondering if you still happened to have a copy somewhere that you could upload? 

It seems that way back in 2012 when the Fairy Mod was updated to support Minecraft Version 1.2.5 and switched from modloader to forge, the download link to the b1.7.3 version was removed from its forum page and nobody backed it up. I have scoured every archive, every page I could waybackmachine to find a copy, and no luck. It seems to be completely dead. Thus, if you have a copy, I'd appreciate it if you could re-upload it. 

Thank you for your time.

**Comment by KodaichiZero** [comment]
Hey, no problem. Looking through my messy backups of old files is a service
I provide for free.

Taking a look here, I'm not super certain about the versions of the game
that I released the fairy mod for, but there's basically two major versions
of the mod itself (not counting the abandoned/unreleased one on my github),
the original Fairy Mod and then the Fairy Factions revamp that came later.
Since I'm pretty sure it isn't too hard to get your hands on Fairy
Factions, I assume the lost one you're talking about is the original fairy
mod. I have a version of the original fairy mod from 2011, which I am
fairly sure was released for Alpha 1.0.13_01 (The versioning of Minecraft
is so confusing now). Or at least that is what that folder is named. I have
attached it. If this isn't what you want, I can dig around a bit more.

There's also a possibility that someone else was maintaining the fairy mod
separately from me for a while and made the 1.7.3 release version. I was
notoriously lazy about updating my mods and I think _303 did a bunch of
them for me for a while, the legend that he is. But I have not been in
contact with him for many years now.

Let me know.

**Comment by KodaichiZero** [comment]
[FairyModV1.zip](https://github.com/KodaichiZero/HeyLookFairies-1.12.2/files/13944474/FairyModV1.zip)
[FairyModV2.zip](https://github.com/KodaichiZero/HeyLookFairies-1.12.2/files/13944487/FairyModV2.zip)

**Comment by KodaichiZero** [comment]
Found another. V1 is for 1.0.12_02, V2 is for 1.0.13_01. I doubt I updated the mod more than this before it became Fairy Factions.

**Comment by GorlathStreams** [comment]
Thank you for the swift reply! 
The version I am looking for was the one you cited as "v6", I believe. It does look like _303 had a hand in its creation, given the text on the thread (https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272418-1-7-3-fairy-mod-v6). I suppose I'll have to track him down? 
That said, I will happily take any versions you can provide as a more complete archive is only beneficial to everyone. As far as I'm aware, all of the links before third parties took over are dead, and 303's mod archive is completely deleted. 
Once again, thank you for your time.

Edit: Also I suppose I should ask for permission to upload these to archive sites for safekeeping, if that's alright with you?

**Comment by KodaichiZero** [comment]
Yeah that's fine. I've given you all I have for the moment.

**Comment by GorlathStreams** [comment]
Alright. Thank you very much, this is far more than I had expected or hoped for.
